### ISSUE TITLE
FP issue related with tx hash

### ISSUE THREAD

**Issue by Ivan1905** [rodri-forta/Forta-Twitter-Bot#1]
Found an issue where the alert is pointing out an non existing address in cases where the tweet mentions a tx hash.

1. [Alert](https://explorer.forta.network/alert/0xd996f5c70f8786479216bea4a7242a65170a914dbe9b03c3a085a21144fee659) - [tweet](https://twitter.com/zachxbt/status/1710653035943247898)
2. [Alert](https://explorer.forta.network/alert/0x0df658f7c3d5883b814a2a9d609427863188e4b38868e0de61b875d1835abd41) - [tweet](https://twitter.com/zachxbt/status/1710686005605392553)

Guess the logic of the bot is cutting the first 42 digits of the tx hash.

**Comment by rodri-forta** [comment]
Thanks ivo! Is now Fixed
